on:
  workflow_run:
    workflows: ["Compile"]
    branches: ["master"]
    types:
     - completed

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: openjdk:11
    name: Deploy
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Compile and Build jars
        run: sh compile_all.sh
      
      - name: Deploy
        run: sh deploy.sh