on: push

name: Compile Java Projects

jobs:
  compile_common:
    runs-on: ubuntu-latest
    name: Compile Common
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
      
      - name: Get Gson
        run: wget -O /tmp/gson.jar https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar
      
      - name: Compile Common
        run: javac -cp ".:/tmp/gson.jar" $(find . -name "*.java")
        shell: bash
        working-directory: Common/src/
  compile_bukkit:
    needs: compile_common
    name: Compile Bukkit
    steps:
      - name: Get Spigot 1.8.8
        run: wget -O /tmp/spigot.1.8.8.jar https://cdn.getbukkit.org/spigot/spigot-1.8.8-R0.1-SNAPSHOT-latest.jar
      
      - name: Copy Common
        run: cp -R Common/src/* Bukkit/src/

      - name: Compile Bukkit on Spigot 1.8.8
        run: javac -cp ".:/tmp/gson.jar;/tmp/spigot.1.8.8.jar" $(find . -name "*.java")
        shell: bash
        working-directory: Bukkit/src/
  compile_bungee:
    needs: compile_common
    name: Compile Bungee
    steps:
      - name: Get BungeeCord
        run: wget -O /tmp/BungeeCord.jar https://ci.md-5.net/job/BungeeCord/lastSuccessfulBuild/artifact/bootstrap/target/BungeeCord.jar
      
      - name: Copy Common
        run: cp -R Common/src/* BungeeCord/src/

      - name: Compile Bungee
        run: javac -cp ".:/tmp/gson.jar;/tmp/BungeeCord.jar" $(find . -name "*.java")
        shell: bash
        working-directory: BungeeCord/src/