on: 
  push:
    branches: [ master ]
  pull_request:

name: Compile & Deploy

jobs:
  compile_java:
    runs-on: ubuntu-latest
    name: Compile Java
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - name: Download libraries
        run: sh scripts/get_libraries.sh

      - name: Compile Common
        run: javac -cp ".:../../libraries/gson.jar" $(find . -name "*.java")
        shell: bash
        working-directory: Common/src/

      - name: Compile Bukkit
        run: sh scripts/compile_bukkit.sh

      - name: Compile Bungee
        run: sh scripts/compile_bungee.sh

      - name: Compile CLI
        run: sh scripts/compile_cli.sh

      - name: Compile Modules
        run: sh scripts/compile_modules.sh
  compile_controller:
    runs-on: ubuntu-latest
    container: node:14.17
    name: Compile Controller
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm install 
        working-directory: ServerController/
      
      - name: Compile ServerController Source
        run: npx tsc
        shell: bash
        working-directory: ServerController/
  deploy:
    if: ${{ github.event_name == 'push'}}
    needs: [ compile_java, compile_controller ]
    runs-on: ubuntu-latest
    name: Deploy
    steps:

      - name: Setup Java JDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
          architecture: 'x64'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Compile and Build jars
        run: sh scripts/compile_all.sh
      
      - name: Deploy
        run: sh scripts/deploy.sh

      - name: Upload Bukkit artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bukkit Plugin
          path: builds/Bukkit.jar

      - name: Upload BungeeCord artifact
        uses: actions/upload-artifact@v2
        with:
          name: BungeeCord Plugin
          path: builds/BungeeCord.jar

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v2
        with:
          name: CLI
          path: builds/CLI.jar

      - name: Upload Modules artifact
        uses: actions/upload-artifact@v2
        with:
          name: Modules
          path: builds/modules/