on: 
  push:
    paths:
      - '**.java'
name: Compile

jobs:
  compile_common:
    runs-on: ubuntu-latest
    name: Compile Common
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
      
      - name: Get Gson
        run: wget -O /tmp/gson.jar https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar
      
      - name: Compile Common
        run: javac -cp ".:/tmp/gson.jar" $(find . -name "*.java")
        shell: bash
        working-directory: Common/src/